providers:
  - aws:
      region: eu-central-1
environments:
  prod:
extra_assets:
_resources_with_network_required:
  - aws_redshift_cluster
  - aws_redshift_cluster_subnet
  - aws_mwaa_environment
_resources_with_iam_required:
  - aws_redshift_cluster
  - aws_mwaa_environment