envs:
  prod:
    backend:
      type: s3
      options:
        key: "<ENTER YOUR VARIABLE VALUE HERE>"
        bucket: "<ENTER YOUR VARIABLE VALUE HERE>"
        region: "<ENTER YOUR VARIABLE VALUE HERE>"
        dynamodb_table: "<ENTER YOUR VARIABLE VALUE HERE>" # LockID as String for partition key
        encrypt: true
default_backend: # Extra backend default definition in case backend-less environment is provided
  type: s3
  options:
    key: "<ENTER YOUR VARIABLE VALUE HERE>"
    bucket: "<ENTER YOUR VARIABLE VALUE HERE>"
    region: "<ENTER YOUR VARIABLE VALUE HERE>"
    dynamodb_table: "<ENTER YOUR VARIABLE VALUE HERE>" # LockID as String for partition key
    encrypt: true
_resources_with_network_required:
  - aws_redshift_cluster
  - aws_redshift_cluster_subnet
_resources_with_iam_required:
  - aws_redshift_cluster